import type { Bike } from './types';
import {
  SCOOTER_4,
  SCOOTER_5,
  CRUISER_2,
  SPORT_2,
  ADV_2,
  HONDA_SCOOTER_1,
  HONDA_SCOOTER_2,
  VESPA_1,
  VESPA_2,
  RE_CLASSIC_1,
  RE_CLASSIC_2,
  RE_HUNTER_1,
  RE_HUNTER_2,
  RE_HUNTER_3,
  YAMAHA_FZ_1,
  YAMAHA_FZ_2,
  KTM_DUKE_1,
  KTM_DUKE_2,
  KTM_DUKE_3,
  BAJAJ_DOMINAR_1,
  BAJAJ_DOMINAR_2,
  RE_HIMALAYAN_1,
  RE_HIMALAYAN_2,
  KTM_RC_1,
  KTM_RC_2,
  KTM_RC_3,
} from './images';

/**
 * Catalog of motorbikes available at our Weligama hub.
 * Models reflect what's actually rented to tourists across Sri Lanka's
 * south coast — auto scooters for first-timers, Royal Enfields for the
 * Galle-to-Mirissa cruisers, KTMs and Yamahas for the spirited riders,
 * and Bajaj Dominars for inland adventures.
 */
export const bikes: Bike[] = [
  {
    id: 'b01',
    slug: 'honda-dio-110',
    name: 'Honda Dio 110',
    model: '2024',
    type: 'Scooter',
    transmission: 'Automatic',
    engineCC: 110,
    topSpeedKph: 85,
    hourlyPriceUSD: 2,
    dailyPriceUSD: 8,
    weeklyPriceUSD: 45,
    images: [HONDA_SCOOTER_1, HONDA_SCOOTER_2, SCOOTER_4],
    features: [
      'Effortless twist-and-go automatic',
      'Lightweight 102 kg — easy in traffic',
      'Under-seat storage for a helmet',
      'Free helmet, lock & phone holder',
    ],
    description:
      "Sri Lanka's most-rented scooter for good reason — friendly, light, fuel-efficient, and stress-free in Weligama traffic. The perfect first bike for travellers who've never ridden before.",
    rating: 4.8,
    reviewCount: 412,
    available: true,
    popular: true,
  },
  {
    id: 'b02',
    slug: 'honda-activa-6g',
    name: 'Honda Activa 6G',
    model: '2024',
    type: 'Scooter',
    transmission: 'Automatic',
    engineCC: 110,
    topSpeedKph: 90,
    hourlyPriceUSD: 2,
    dailyPriceUSD: 9,
    weeklyPriceUSD: 50,
    images: [HONDA_SCOOTER_2, HONDA_SCOOTER_1, SCOOTER_5],
    features: [
      'Smooth eSP+ engine',
      'External fuel filler — quick top-ups',
      'LED headlight standard',
      'Free helmet, lock & phone holder',
    ],
    description:
      'A workhorse of a commuter scooter. Ride it to Mirissa for breakfast, ride it to Coconut Tree Hill for sunset, ride it home — it just keeps going.',
    rating: 4.7,
    reviewCount: 286,
    available: true,
  },
  {
    id: 'b03',
    slug: 'vespa-sxl-150',
    name: 'Vespa SXL 150',
    model: '2024',
    type: 'Scooter',
    transmission: 'Automatic',
    engineCC: 149,
    topSpeedKph: 100,
    hourlyPriceUSD: 4,
    dailyPriceUSD: 22,
    weeklyPriceUSD: 130,
    images: [VESPA_1, VESPA_2, SCOOTER_5],
    features: [
      '150cc fuel-injected engine',
      'Iconic steel monocoque body',
      'Bluetooth connectivity & ASR',
      'Free helmet, lock & phone holder',
    ],
    description:
      'Premium Italian style with the soul to match. Roll up to Galle Fort with the windows down on a Vespa and you understand what slow travel really means.',
    rating: 4.9,
    reviewCount: 134,
    available: true,
    popular: true,
  },
  {
    id: 'b04',
    slug: 'royal-enfield-classic-350',
    name: 'Royal Enfield Classic 350',
    model: '2024',
    type: 'Cruiser',
    transmission: 'Manual',
    engineCC: 349,
    topSpeedKph: 130,
    hourlyPriceUSD: 5,
    dailyPriceUSD: 28,
    weeklyPriceUSD: 165,
    images: [RE_CLASSIC_1, RE_CLASSIC_2, CRUISER_2],
    features: [
      'Iconic 349cc single-cylinder thump',
      'Tripper navigation pod',
      'Dual-channel ABS',
      'Long-travel touring seat',
    ],
    description:
      'The bike every traveller pictures riding through Sri Lanka. Endless torque, that unmistakable thump, and the build to handle every coastal curve from Tangalle to Hikkaduwa.',
    rating: 4.9,
    reviewCount: 198,
    available: true,
    popular: true,
  },
  {
    id: 'b05',
    slug: 'royal-enfield-hunter-350',
    name: 'Royal Enfield Hunter 350',
    model: '2024',
    type: 'Cruiser',
    transmission: 'Manual',
    engineCC: 349,
    topSpeedKph: 130,
    hourlyPriceUSD: 4,
    dailyPriceUSD: 24,
    weeklyPriceUSD: 140,
    images: [RE_HUNTER_1, RE_HUNTER_2, RE_HUNTER_3],
    features: [
      'Lighter, more flickable Hunter chassis',
      '349cc J-platform engine',
      'Modern roadster ergonomics',
      'Dual-channel ABS',
    ],
    description:
      "All the Royal Enfield character in a friendlier, more agile package. If the Classic feels intimidating, the Hunter is your bike — easier in town, just as soulful on the open road.",
    rating: 4.7,
    reviewCount: 112,
    available: true,
  },
  {
    id: 'b06',
    slug: 'yamaha-fz-s-v3',
    name: 'Yamaha FZ-S V3',
    model: '2024',
    type: 'Sport',
    transmission: 'Manual',
    engineCC: 149,
    topSpeedKph: 115,
    hourlyPriceUSD: 3,
    dailyPriceUSD: 16,
    weeklyPriceUSD: 95,
    images: [YAMAHA_FZ_1, YAMAHA_FZ_2, SPORT_2],
    features: [
      'Aggressive streetfighter styling',
      '149cc fuel-injected engine',
      'Single-channel ABS',
      'Wide rear tyre for grip',
    ],
    description:
      "Light, snappy, and confidence-inspiring. The FZ-S is a favourite of seasoned riders who want something more spirited than a scooter without committing to a full sport bike.",
    rating: 4.6,
    reviewCount: 167,
    available: true,
  },
  {
    id: 'b07',
    slug: 'ktm-duke-250',
    name: 'KTM Duke 250',
    model: '2024',
    type: 'Sport',
    transmission: 'Manual',
    engineCC: 248,
    topSpeedKph: 145,
    hourlyPriceUSD: 5,
    dailyPriceUSD: 32,
    weeklyPriceUSD: 190,
    images: [KTM_DUKE_1, KTM_DUKE_2, KTM_DUKE_3],
    features: [
      '248cc liquid-cooled single',
      'Trellis frame & WP suspension',
      'Cornering ABS standard',
      'TFT instrument cluster',
    ],
    description:
      "Sharp, quick, and very alive. A favourite for the twisty inland roads heading up to Ella and Nuwara Eliya. Bring your A-game — this one rewards smooth riders.",
    rating: 4.8,
    reviewCount: 89,
    available: true,
  },
  {
    id: 'b08',
    slug: 'bajaj-dominar-400',
    name: 'Bajaj Dominar 400',
    model: '2023',
    type: 'Adventure',
    transmission: 'Manual',
    engineCC: 373,
    topSpeedKph: 160,
    hourlyPriceUSD: 5,
    dailyPriceUSD: 30,
    weeklyPriceUSD: 175,
    images: [BAJAJ_DOMINAR_1, BAJAJ_DOMINAR_2, ADV_2],
    features: [
      '373cc liquid-cooled engine',
      'Touring-friendly upright posture',
      'Dual-channel ABS',
      'Generous 13L fuel tank',
    ],
    description:
      "Built for distance. Whether you're heading inland to Yala, up to Ella, or all the way to the cultural triangle, the Dominar eats kilometres without complaint.",
    rating: 4.7,
    reviewCount: 76,
    available: true,
  },
  {
    id: 'b09',
    slug: 'royal-enfield-himalayan-450',
    name: 'Royal Enfield Himalayan 450',
    model: '2024',
    type: 'Adventure',
    transmission: 'Manual',
    engineCC: 452,
    topSpeedKph: 150,
    hourlyPriceUSD: 7,
    dailyPriceUSD: 42,
    weeklyPriceUSD: 245,
    images: [RE_HIMALAYAN_1, RE_HIMALAYAN_2, ADV_2],
    features: [
      'Long-travel adventure suspension',
      '452cc Sherpa engine',
      'Switchable rear ABS',
      '21" front wheel for rough roads',
    ],
    description:
      'The off-road ready Himalayan opens up Sri Lanka beyond the asphalt. Tea plantation tracks, gravel roads to hidden beaches, and the long ride to Knuckles all become possible.',
    rating: 4.9,
    reviewCount: 54,
    available: true,
  },
  {
    id: 'b10',
    slug: 'ktm-rc-390',
    name: 'KTM RC 390',
    model: '2024',
    type: 'Sport',
    transmission: 'Manual',
    engineCC: 373,
    topSpeedKph: 180,
    hourlyPriceUSD: 8,
    dailyPriceUSD: 48,
    weeklyPriceUSD: 280,
    images: [KTM_RC_1, KTM_RC_2, KTM_RC_3],
    features: [
      'Race-bred 373cc single',
      'Quickshifter standard',
      'Cornering ABS & TC',
      'Aerodynamic full fairing',
    ],
    description:
      'A pocket-rocket for experienced riders. Bring it out on the empty Southern Expressway early morning and you remember why supersports exist.',
    rating: 4.8,
    reviewCount: 41,
    available: true,
  },
];

export function findBikeBySlug(slug: string | undefined): Bike | undefined {
  if (!slug) return undefined;
  return bikes.find((b) => b.slug === slug);
}

export function getRelatedBikes(currentSlug: string, limit = 3): Bike[] {
  const current = findBikeBySlug(currentSlug);
  if (!current) return bikes.slice(0, limit);
  const sameType = bikes.filter((b) => b.slug !== currentSlug && b.type === current.type);
  const others = bikes.filter((b) => b.slug !== currentSlug && b.type !== current.type);
  return [...sameType, ...others].slice(0, limit);
}
